export default {
  LOAD_RECIPES: 'LOAD_RECIPES',
  DELETE_RECIPE: 'DELETE_RECIPE',
  DELETE_RECIPE_ERROR: 'DELETE_RECIPE_ERROR',
  ADD_RECIPE: 'ADD_RECIPE',
  ADD_RECIPE_ERROR: 'ADD_RECIPE_ERROR',
  UPDATE_RECIPE: 'UPDATE_RECIPE',
  LOAD_RECIPE: 'LOAD_RECIPE',
  LOAD_RECIPE_ERROR: 'LOAD_RECIPE_ERROR',

  LOAD_USERS: 'LOAD_USERS',
  DELETE_USER: 'DELETE_USER',
  ADD_USER: 'ADD_USER',
  ADD_USER_ERROR: ' ADD_USER_ERROR',
  UPDATE_USER: 'UPDATE_USER',
  LOAD_USER: 'LOAD_USER',
  LOAD_USER_ERROR: 'LOAD_USER_ERROR',
};
